var labels = {
    'es': {
        tab_guest_list: 'GUEST LIST',
        tab_clubs: 'CLUBS',
        tab_life: 'LIFE',
        tab_promos: 'PROMOS',
        tab_profile: 'MI PERFIL',
        header_guest_list: 'Guest List',
        header_clubs: 'Clubs',
        back_to_my_guest_list: 'VOLVER A MI GUEST LIST',
        my_data: 'Mis Datos',
        name: 'Nombre:',
        email: 'Email:',
        phone: 'Telefono:',
        edit: 'EDITAR',
        idiom: 'Idioma',
        alerts: 'Alertas',
        setup_my_data: 'CONFIGURAR MIS DATOS',
        validate: 'VALIDAR POR EL RESPONSABLE DEL CLUB',
        guest_list: 'GUEST LIST:',
        club: 'Club:',
        address: 'Dirección:',
        hour: 'Horario:',
        metro: 'Metro:',
        ambient: 'Ambiente:',
        accept_card: 'Acepta Tarjeta',
        fill_form: 'rellena este pequeño formulario. Este proceso sólo es necesario una vez',
        first_name: 'Nombre:',
        last_name: 'Apellidos:',
        persons: 'Nº de personas:',
        conditions: 'aceptar condiciones',
        confirm: 'CONFIRMAR',
        sessions: 'Sesiones:',
        open: 'Abierto:',
        type: 'Tipo de cocina:',
        save: 'Guardar',
        in: ' en ',
        user_first_name_required: 'Nombre es requerido',
        user_last_name_required: 'Apellido es requerido',
        user_email_required: 'Email es requerido',
        user_email_invalid: 'Direccion de Email inválida',
        user_phone_required: 'Telefono es requerido',
        user_conditions_required: 'Debe aceptar las condiciones',
        no_guest_list: 'No tienes ningún GUEST LIST. Entra en la sección y elige tus sesiones',
        no_data: 'No hay datos para mostrar',
        no_sessions: 'No hay sessiones disponibles',
        no_clubs: 'No hay clubs disponibles',
        no_life: 'No hay life disponibles',
        no_promos: 'No hay promos disponibles',
        hi: 'Hola',
        complete_nro_persons: 'completa el n° de personas que asistiréis',
        to_session: 'a la sessión',
        to_day: 'del día',
        perfect: 'Perfecto!',
        you_are_in_guest_list: 'ya estás en la guest list de ',
        for_session: 'para la ',
        present_invitation: 'presenta la invitación que te hemos guardado',
        in_seccion: 'en la sección',
        this_app: 'de este app',
        club_door: 'en la puerta del club',
        my_profile: 'MI PERFIL',
        profile: 'mi perfil',
        alert: 'ALERTA',
        accept: 'Aceptar',
        yes: 'Si',
        no: 'No',
        call: 'LLAMAR',
        total_persons: 'personas',
        access_conditions: 'Condiciones de acceso:',
        age: 'Edad:',
        dress_code: 'Dress Code:',
        ask_golden: 'PREGUNTA POR GOLDEN VIP LIST<br>O MUESTRA ESTA PANTALLA'
    },
    'en': {
        tab_guest_list: 'GUEST LIST',
        tab_clubs: 'CLUBS',
        tab_life: 'LIFE',
        tab_promos: 'PROMOS',
        tab_profile: 'MY PROFILE',
        header_guest_list: 'Guest List',
        header_clubs: 'Clubs',
        back_to_my_guest_list: 'BACK TO MY GUEST LIST',
        my_data: 'My Info',
        name: 'Name:',
        email: 'Email:',
        phone: 'Phone:',
        edit: 'EDIT',
        idiom: 'Language',
        alerts: 'Notifications',
        setup_my_data: 'SETUP MY INFO',
        validate: 'VALIDATE BY CLUB RESPONSABLE',
        guest_list: 'GUEST LIST:',
        club: 'Club:',
        address: 'Address:',
        hour: 'Schedule:',
        metro: 'Metro:',
        ambient: 'Ambient:',
        accept_card: 'Accept Card',
        fill_form: 'fill this few form, This process is only required once',
        first_name: 'Name:',
        last_name: 'Surename:',
        persons: 'Nº of persons:',
        conditions: 'accept conditions',
        confirm: 'CONFIRM',
        sessions: 'Sessions:',
        open: 'Open:',
        type: 'Type of kitchen:',
        save: 'Save',
        in: ' in ',
        user_first_name_required: 'Name is required',
        user_last_name_required: 'Surename is required',
        user_email_required: 'Email is required',
        user_email_invalid: 'Invalid email address',
        user_phone_required: 'Phone is required',
        user_conditions_required: 'You must accept conditions',
        no_guest_list: 'You have no GUEST LIST. Enter the section and select your sessions',
        no_data: 'There is no data to show',
        no_sessions: 'There is no sessions available',
        no_clubs: 'There is no clubs available',
        no_life: 'There is no life available',
        no_promos: 'There is promos available',
        hi: 'Hi',
        complete_nro_persons: 'Complete the n° of people who will attend',
        to_session: 'to session',
        to_day: 'of the day',
        perfect: 'Perfect!',
        you_are_in_guest_list: "and you're on the guest list of ",
        for_session: 'for ',
        present_invitation: "presents the invitation that we've kept",
        in_seccion: 'in section',
        this_app: 'of this app',
        club_door: 'in front of the club',
        my_profile: 'MY PROFILE',
        profile: 'my profile',
        alert: 'ALERT',
        accept: 'Accept',
        yes: 'Yes',
        no: 'No',
        call: 'CALL',
        total_persons: 'persons',
        access_conditions: 'Access Conditions:',
        age: 'Age:',
        dress_code: 'Dress Code:',
        ask_golden: 'ASK FOR GOLDEN VIP LIST <br>OR SAMPLE THIS SCREEN'
    }
};